####################################################################################
#
# Generated by eda_pt_script.tcl	#1
#              eda_pt_conversion.tcl	#1
#              in c:/altera/91sp2/quartus/common/tcl/internal/eda_pt/.
#
# Quartus:  Version 9.1 Build 350 03/24/2010 Service Pack 2 SJ Web Edition
#
# Project:  final
# Revision: final
#
# Date: Tue Jun 15 14:41:48 +0800 2021
#
####################################################################################


set _col16 [ get_pins {comb_5|current_state.1110.q}]



set _col3 [ get_ports {clk}]



set _col14 [ get_pins {comb_4|c|clk_out.q}]



set _col15 [ get_pins {{comb_5|score[0].combout}}]



